trigger:
- none

pr:
  branches:
    include:
    - main

schedules:
- cron: "0 4 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Nightly Test Run
  branches:
    include:
    - main
  always: true

parameters:
- name: forcePushToProd
  displayName: Force Push to Production
  type: boolean
  default: false

variables:
  buildMajor: 3
  buildMinor: 0
  buildBranch: $[replace(variables['Build.SourceBranch'], '/', '.')]

pool: 'vmss-ado-chs-nonprod-001'

name: $(buildMajor).$(buildMinor).$(Rev:r)-$(buildBranch)

resources:
  repositories:
  - repository: he-fms-deployment
    type: git
    name: 'FMS/he-fms-deployment'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: pipelines/azure-pipelines-build.yml@he-fms-deployment
  parameters:
    dotnetVersion: '8.0.x'
    forcePushToProd: ${{ parameters.forcePushToProd }}
