trigger: none

variables:
  buildMajor: 1
  buildMinor: 1
  buildBranch: $[replace(variables['Build.SourceBranch'], '/', '.')]

parameters:
- name: dockerPush
  displayName: Push Docker Image
  type: boolean
  default: true
- name: dockerPushProd
  displayName: Push Docker Image to Prod
  type: boolean
  default: false

pool: 'vmss-ado-chs-nonprod-001'

name: $(buildMajor).$(buildMinor).$(Rev:r)-$(buildBranch)

resources:
  repositories:
  - repository: he-fms-deployment
    type: git
    name: 'FMS/he-fms-deployment'
    ref: 'pr-pipeline'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'docker-build'

stages:
- template: pipelines/azure-pipelines-build.yml@he-fms-deployment
  parameters:
    dotnetVersion: '8.0.x'
    dockerPush: ${{ parameters.dockerPush }}
    dockerPushProd: ${{ parameters.dockerPushProd }}
