trigger:
  branches:
    include:
    - main
variables:
  tag: "$(Build.BuildId)"

parameters:
- name: forcePushToProd
  displayName: Force Push to Production
  type: boolean
  default: false

pool: 'vmss-ado-chs-nonprod-001'

resources:
  repositories:
  - repository: he-fms-deployment
    type: git
    name: 'FMS/he-fms-deployment'
    ref: 'main'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: pipelines/azure-pipelines-build.yml@he-fms-deployment
  parameters:
    tag: "$(Build.BuildId)"
    dotnetVersion: '8.0.x'
    forcePushToProd: ${{ parameters.forcePushToProd }}
